### ISSUE TITLE
Required signatures should be the same on both sides

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-monitor#2]

**Comment by pablofullana** [comment]
Requires #7

**Comment by patitonar** [comment]
@akolotov It seems that this issue was already solved on this commit https://github.com/poanetwork/bridge-monitor/commit/451dbdc5c0fde8081812ae01c0f020d905b22e58. 
The endpoint `/` shows a property `"requiredSignaturesMatch": true` to indicate if required signatures are the some on both sides. So I think we can close this issue.

**Comment by akolotov** [comment]
> @akolotov It seems that this issue was already solved on this commit [451dbdc](https://github.com/poanetwork/bridge-monitor/commit/451dbdc5c0fde8081812ae01c0f020d905b22e58).
> The endpoint `/` shows a property `"requiredSignaturesMatch": true` to indicate if required signatures are the same on both sides. So I think we can close this issue.

Agree. Closing the issue.
